# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AdventureSFU' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AdventureSFU
pod 'Firebase/Core'
pod ‘Firebase/Database’
pod ‘Firebase/Storage’
  target 'AdventureSFUTests' do
    inherit! :search_paths
    # Pods for testing
pod 'Firebase/Core'
pod ‘Firebase/Database’
pod ‘Firebase/Storage’
  end

  target 'AdventureSFUUITests' do
    inherit! :search_paths
    # Pods for testing
pod ‘Firebase/Core’
pod ‘Firebase/Database’
pod ‘Firebase/Storage’
  end

end
