# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AdventureSFU' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AdventureSFU
pod 'Firebase/Core'
pod ‘Firebase/Database’
pod ‘Firebase/Storage’
pod 'Firebase/Auth'
pod ‘Mapbox-iOS-SDK’, ‘~> 3.4’
pod 'MapboxDirections.swift', :git => 'https://github.com/mapbox/MapboxDirections.swift.git', :commit => 'ceaf58b780fc17ea44a9150041b602d017c1e567'
pod 'MapboxNavigation.swift', :git => 'https://github.com/mapbox/MapboxNavigation.swift.git', :tag => 'v0.0.4'

  target 'AdventureSFUTests' do
    inherit! :search_paths
    # Pods for testing
pod 'Firebase/Core'
pod ‘Firebase/Database’
pod ‘Firebase/Storage’
pod 'Firebase/Auth'
pod 'MapboxDirections.swift', :git => 'https://github.com/mapbox/MapboxDirections.swift.git', :commit => 'ceaf58b780fc17ea44a9150041b602d017c1e567'
pod 'MapboxNavigation.swift', :git => 'https://github.com/mapbox/MapboxNavigation.swift.git', :tag => 'v0.0.4'

  end

  target 'AdventureSFUUITests' do
    inherit! :search_paths
    # Pods for testing
pod ‘Firebase/Core’
pod ‘Firebase/Database’
pod ‘Firebase/Storage’
pod 'Firebase/Auth'
pod 'MapboxDirections.swift', :git => 'https://github.com/mapbox/MapboxDirections.swift.git', :commit => 'ceaf58b780fc17ea44a9150041b602d017c1e567'
pod 'MapboxNavigation.swift', :git => 'https://github.com/mapbox/MapboxNavigation.swift.git', :tag => 'v0.0.4'
  end

end
